[Feat] 위키 등록 백엔드 API (#23)
beyond-sw-camp/be06-fin-SENAGAE-Enadu pull request #130
Opened 2024-09-08 09:37 UTC by jimnyy

## 연관 이슈
close #23

## 작업 내용
- 위키 등록시 사용자 req에 의해 썸네일, 위키 내용 저장
- 위키 등록할 때(수정 x, 젤 처음 등록) 제목, 내용, 카테고리가 필요한데 위키 Entity에는 title이 없었음. => Wiki Entity에 title 추가
- Wiki와 Category 연관관계 수정. => OneToOne에서 ManyToOne
- content 안의 사진 업로드시, 사진 경로 URL은 컬럼의 content에 같이 저장 처리

## 스크린샷 (선택)
![image](https://github.com/user-attachments/assets/85ea3d1f-00cc-458e-a3c5-b11ae2a97c53)

## 리뷰 요구사항 (선택)

2024-09-08 09:43 UTC, sue06004 requested changes
리뷰한거만 추가하면 될듯

2024-09-08 09:43 UTC, sue06004 commented on backend/src/main/java/org/example/backend/Wiki/Service/WikiService.java
> +
이렇게 하면 wiki에 latest wiki가 저장 안됌. 수정 바람

2024-09-08 09:43 UTC, sue06004 commented on backend/src/main/java/org/example/backend/Wiki/Controller/WikiController.java
> +        String thumbnailImgUrl = cloudFileUploadService.uploadImg(thumbnail); //thumbnail 경로를 thumbnailImgUrl 에 반환
썸네일 설정 안하면 기본 썸네일 설정해주는 것도 추가 해주세요

2024-09-08 13:42 UTC, jimnyy commented on backend/src/main/java/org/example/backend/Wiki/Service/WikiService.java
> +
![image](https://github.com/user-attachments/assets/d7e57da5-3ee5-4cba-879c-c2ed7b279504)
수정 완료

2024-09-08 18:18 UTC, jimnyy commented on backend/src/main/java/org/example/backend/Wiki/Controller/WikiController.java
> +        String thumbnailImgUrl = cloudFileUploadService.uploadImg(thumbnail); //thumbnail 경로를 thumbnailImgUrl 에 반환
![image](https://github.com/user-attachments/assets/f80385be-c56b-4ba2-be29-a439325a6fd1)
추가 완료

2024-09-08 18:32 UTC, jimnyy commented on backend/src/main/java/org/example/backend/Wiki/Controller/WikiController.java
> +        String thumbnailImgUrl = cloudFileUploadService.uploadImg(thumbnail); //thumbnail 경로를 thumbnailImgUrl 에 반환
![image](https://github.com/user-attachments/assets/cea3356a-836f-4ad4-b692-1f25ed75e1ce)
추가 완료

2024-09-09 03:09 UTC, sue06004 approved these changes
굿

2024-09-09 03:09 UTC, sue06004 commented on backend/src/main/java/org/example/backend/File/Service/CloudFileUploadService.java
> +    public List<String> basicThumbnailList = Arrays.asList("https://jimmny.s3.ap-northeast-2.amazonaws.com/IMAGE/2024/09/08/BasicImg3.png","https://jimmny.s3.ap-northeast-2.amazonaws.com/IMAGE/2024/0
상수는 private final static 으로 변경해주세요.

2024-09-09 03:11 UTC, jimnyy commented on backend/src/main/java/org/example/backend/File/Service/CloudFileUploadService.java
> +    public List<String> basicThumbnailList = Arrays.asList("https://jimmny.s3.ap-northeast-2.amazonaws.com/IMAGE/2024/09/08/BasicImg3.png","https://jimmny.s3.ap-northeast-2.amazonaws.com/IMAGE/2024/0
수정 했습니다.

2024-09-09 03:11 UTC, merged