[Feat] qna 상세 조회 구현
beyond-sw-camp/be06-fin-SENAGAE-Enadu pull request #133
Opened 2024-09-09 01:12 UTC by ashd89

## 연관 이슈
close #37

## 작업 내용
- question / answer / answerComment 3단계로 나누어 단계별 조회 시스템 구현
- 리스트 스트림을 통해 맵핑하여 연결되도록 설정 
- user데이터를 사용하는 checklike/hate/scrap의 경우 미완성

## 스크린샷 (선택)

## 리뷰 요구사항 혹은 기타 (선택)

2024-09-09 05:05 UTC, dyun23 reviewed
LGTM 😊

2024-09-09 14:50 UTC, sue06004 requested changes
저것만 수정하면 될듯 굿굿

2024-09-09 14:50 UTC, sue06004 commented on backend/src/main/java/org/example/backend/Qna/Controller/QuestionController.java
> +    public BaseResponse<Void> saveQuestion(@RequestBody CreateQuestionReq req) {
우리 등록 할 때 반환값으로 등록된 데이터 id 반환해주기로 했어 api 명세서엔 없는데 추가해줘야 할 듯

2024-09-09 14:50 UTC, sue06004 commented on backend/src/main/java/org/example/backend/Qna/Controller/QuestionController.java
> +    //qna 목록 조회
헷갈리는 주석은 지워줘

2024-09-10 04:50 UTC, dlrkdms125 commented
👍

2024-09-10 06:48 UTC, ashd89 commented
전부 수정 완료!

2024-09-10 06:48 UTC, merged