[Feat] 에러 아카이브 게시판 등록
beyond-sw-camp/be06-fin-SENAGAE-Enadu pull request #141
Opened 2024-09-09 11:53 UTC by dlrkdms125

[Feat] 에러 아카이브 게시판 등록
에러 아카이브 게시판에 글을 등록시 @Authenticationprincipal를 이용해 CustomUserDetails를 받도록 설정
로그인한 사용자의 CustomUserDetails의 이메일 정보를 이용하여 해당 이메일로 사용자를 조회
사용자의 Id를 errorarchive board 테이블에 저장

category의 외래키컬럼의 unique를 취소해서
같은 카테고리ID에 다른 title, content로 글을 작성할 수 있도록 설정

2024-09-09 12:25 UTC, sue06004 requested changes
다 수정하고 말해주세요

2024-09-09 12:25 UTC, sue06004 commented on backend/src/main/java/org/example/backend/ErrorArchive/Service/ErrorArchiveService.java
> +@AllArgsConstructor
RequiredArgsContructor로 바꿔줘

2024-09-09 12:25 UTC, sue06004 commented on backend/src/main/java/org/example/backend/ErrorArchive/Service/ErrorArchiveService.java
> +    @Autowired
이거 삭제

2024-09-09 12:25 UTC, sue06004 commented on backend/src/main/java/org/example/backend/ErrorArchive/Model/Req/RegisterErrorArchiveReq.java
> +@AllArgsConstructor
필요 없어서 삭제 바람

2024-09-09 12:25 UTC, sue06004 commented on backend/src/main/java/org/example/backend/ErrorArchive/Model/Res/ErrorArchiveRes.java
> +    private Long id;
지금은 필요없는데 나중에 상세 조회 할 때 필요 할 거 같으니 잘 기억하고 쓰도록

2024-09-09 12:25 UTC, sue06004 commented on backend/src/main/java/org/example/backend/ErrorArchive/Controller/ErrorArchiveController.java
> +    public BaseResponse<Void> register(
반환 타입은 void가 아니라 등록된 archive의 id를 반환하도록 수정

2024-09-10 04:48 UTC, dyun23 commented
이하동문입니다 수정하면 될 것 같아요

2024-09-10 05:12 UTC, ashd89 requested changes

2024-09-10 05:12 UTC, ashd89 commented on backend/src/main/java/org/example/backend/ErrorArchive/Service/ErrorArchiveService.java
> +        Optional<Category> category = categoryRepository.findById(registerErrorArchiveReq.getCategoryId());
user email로 조회보다 id로 조회하면 더 효율적일 것 같습니다!

2024-09-11 08:40 UTC, dlrkdms125 commented on backend/src/main/java/org/example/backend/ErrorArchive/Model/Res/ErrorArchiveRes.java
> +    private Long id;
ErrorArchiveRes 삭제함

2024-09-11 08:52 UTC, dyun23 reviewed
굿!

2024-09-11 08:53 UTC, merged