[Feat] 에러 아카이브 axios 연결, 카테고리 모달창 연결(#71)
beyond-sw-camp/be06-fin-SENAGAE-Enadu pull request #165
Opened 2024-09-11 03:24 UTC by dlrkdms125

## 연관 이슈
close #71 

## 작업 내용
상위 카테고리 검색 버튼을 누르면 상위 카테고리 선택 모달창이 뜨고 그 모달창에서 확인 버튼을 누르면, 하위 카테고리 선택 모달창이 뜨도록 설정
상위 카테고리 모달창에서 카테고리 선택 후 닫기 버튼 누르면 상위 카테고리 선택한 항목만 표시

response가 제목, 내용, 카테고리Id이므로, errorArchive 객체에 title, content, categoryId를 담아서 
객체에 접근해서 데이터를 얻음

subcategory null인지 확인해서 어떤거를 erroArchive 안에 넣어줄지 판별해서 id 넣어주는 거를 추후 수정
openSuperCategoryModal, closeSuperCategoryModal 각각 메소드 만들지 않고, if-else문으로 추후 수정

## 스크린샷 (선택)
<img width="804" alt="image" src="https://github.com/user-attachments/assets/5ee2a27e-2d6c-4d4c-9605-f901c6fc0aad">

## 리뷰 요구사항 혹은 기타 (선택)

2024-09-11 08:58 UTC, sue06004 requested changes
수고했으

2024-09-11 08:58 UTC, sue06004 commented on frontend/src/pages/ErrorArchiveRegisterPage.vue
> +        await this.errorArchiveStore.registerErrorArchive();
이거는 없어도 되는거 아닌가...

2024-09-11 09:03 UTC, dlrkdms125 commented on frontend/src/pages/ErrorArchiveRegisterPage.vue
> +        await this.errorArchiveStore.registerErrorArchive();
맞네 앞으로 콘솔 창 잘 보겠습니당

2024-09-11 09:03 UTC, dyun23 commented on frontend/src/components/errorarchive/ErrorArchiveRegisterComponent.vue
> +      // subcategory null인지 확인해서 어떤거를 erroArchive 안에 넣어줄지 판별해서 id 넣어주기
이 부분 주석 지워주세용

2024-09-11 09:03 UTC, dyun23 commented on frontend/src/components/errorarchive/ErrorArchiveRegisterComponent.vue
> +        // 목록페이지, 상세페이지 보통은 보여주는데 일단은 임시로 '/''
주석만 달아두고 왜 안 바꿔줘요ㅠ

2024-09-11 09:58 UTC, ashd89 commented
LGTM

2024-09-12 03:28 UTC, ashd89 reviewed
LGTM

2024-09-14 14:26 UTC, merged