[Feat] 위키 목록 조회 API 구현 (#26)
beyond-sw-camp/be06-fin-SENAGAE-Enadu pull request #167
Opened 2024-09-11 07:33 UTC by jimnyy

## 연관 이슈
close #26 

## 작업 내용
📌 위키 목록 전체 조회 기능
- 생성일 기준으로 최신순 정렬 처리
- 제목, 내용, 썸네일, 카테고리 출력
- 페이징 처리 (eq에 page, size 입력 안해도 size 20으로 고정 처리)

## 스크린샷 (선택)

## 리뷰 요구사항 혹은 기타 (선택)
예외처리는 필요없는 것 같아서 안했는데, 확인해보고 리뷰 부탁드려용

2024-09-11 08:27 UTC, sue06004 requested changes
굿굿

2024-09-11 08:27 UTC, sue06004 commented on backend/src/main/java/org/example/backend/Wiki/Service/WikiService.java
> +        Pageable pageable = PageRequest.of(wikiListReq.getPage(), 20, Sort.by(Sort.Direction.DESC, "latestWiki.createdAt"));
20이 아니라 wikiListReq.getSize()로 변경 부탁

2024-09-11 09:07 UTC, dyun23 commented on backend/src/main/java/org/example/backend/Wiki/Model/Req/WikiListReq.java
> +public class WikiListReq {
우리 도메인 앞에 안 두기로 하지 않았었나용?

2024-09-11 10:02 UTC, ashd89 requested changes

2024-09-11 10:02 UTC, ashd89 commented on backend/src/main/java/org/example/backend/Wiki/Controller/WikiController.java
> +        if (wikiRegisterReq.getCategoryId() == null) {
위키의 카테고리 관련 부분이면 위키에서 에러 코드를 새로 할당하는게 맞을까 해당 카테고리가 없는 에러가 있는걸로 알고 있어서 협의 해야할 듯

2024-09-12 01:27 UTC, jimnyy commented on backend/src/main/java/org/example/backend/Wiki/Service/WikiService.java
> +        Pageable pageable = PageRequest.of(wikiListReq.getPage(), 20, Sort.by(Sort.Direction.DESC, "latestWiki.createdAt"));
수정 완료

2024-09-12 01:27 UTC, jimnyy commented on backend/src/main/java/org/example/backend/Wiki/Model/Req/WikiListReq.java
> +public class WikiListReq {
수정 완료

2024-09-12 01:27 UTC, jimnyy commented on backend/src/main/java/org/example/backend/Wiki/Controller/WikiController.java
> +        if (wikiRegisterReq.getCategoryId() == null) {
수정 완료

2024-09-12 01:28 UTC, jimnyy commented
수정 완료

2024-09-12 01:29 UTC, merged