[Fix] 댓글을 자기참조 null에 관한 에러처리
beyond-sw-camp/be06-fin-SENAGAE-Enadu pull request #178
Opened 2024-09-12 07:31 UTC by ashd89

## 연관 이슈
close #37 

## 작업 내용
상세 조회 시 상위 댓글을 통해 그 id를 조회할 때 발생하는 null에 대한 접근 에러를 해결 

## 스크린샷 (선택)

## 리뷰 요구사항 혹은 기타 (선택)

2024-09-12 14:01 UTC, sue06004 requested changes
수고했으

2024-09-12 14:01 UTC, sue06004 commented on backend/src/main/java/org/example/backend/Qna/model/Res/GetAnswerCommentDetailListRes.java
>  @AllArgsConstructor
필요없는 어노테이션 정리 해줘 Getter랑 Builder만 있으면 될거야 아마

2024-09-12 14:01 UTC, sue06004 commented on backend/src/main/java/org/example/backend/Qna/model/Res/GetAnswerDetailListRes.java
>  @AllArgsConstructor
여기도

2024-09-12 14:01 UTC, sue06004 commented
merge하고 수정해서 pr 올리지 말고 그냥 바로 수정해서 push 한 다음에 merge 하는게 좋을듯

2024-09-13 08:30 UTC, ashd89 commented
확인했고 수정 중입니다! 카테고리 OneToMany는 일단 코드 다 짜고 하려했어서 이제 수정 중!

2024-09-15 11:12 UTC, merged