[Feat] 위키 상세조회 API (#27)
beyond-sw-camp/be06-fin-SENAGAE-Enadu pull request #181
Opened 2024-09-12 14:24 UTC by jimnyy

## 연관 이슈
close #27

## 작업 내용
📌위키 상세 조회
- 위키(최신버전) 상세조회 기능 구현
- 로그인 한 유저일 시, 스크랩 여부 확인하고 T/F 반환
- 미로그인 유저일 시, 스크랩 여부 fale로 반환
- 제목, 내용, 카테고리, 버전, 스크랩 여부 반환

## 스크린샷 (선택)
![Uploading image.png…]()

## 리뷰 요구사항 혹은 기타 (선택)

2024-09-12 15:02 UTC, sue06004 requested changes
🚨로직 수정해야함!🚨

2024-09-12 16:08 UTC, jimnyy commented on backend/src/main/java/org/example/backend/Wiki/Controller/WikiController.java
> +        System.out.println(customUserDetails);
디버깅 해본다고 ㅋㅎㅋㅎ 삭제 했슴다

2024-09-12 16:21 UTC, jimnyy commented on backend/src/main/java/org/example/backend/Wiki/Service/WikiService.java
> +        WikiContent wikiContent = wikiContentRepository.findById(wiki.getId()).orElseThrow(() -> new InvalidWikiException(BaseResponseStatus.WIKI_NOT_FOUND_DETAIL));
버전으로도 조회 해야 함 => 이건 뭔 말이세요? 최신위키만 출력할 거라 버전으로 조회는 안했는데요

2024-09-12 17:28 UTC, jimnyy commented on backend/src/main/java/org/example/backend/Wiki/Controller/WikiController.java
> +        return new BaseResponse<>(wikiService.detail(getWikiDetailReq,customUserDetails));
수정 완료

2024-09-12 18:33 UTC, jimnyy commented on backend/src/main/java/org/example/backend/Wiki/Service/WikiService.java
> +                .version(wikiContent.getVersion())
수정 완료

2024-09-13 05:15 UTC, sue06004 requested changes
다시하도록

2024-09-13 05:15 UTC, sue06004 commented on backend/src/main/java/org/example/backend/Wiki/Service/WikiService.java
> +        return wikiScrapRepository.findByUserIdAndWikiContentId(userId, latestWiki.getId()).isPresent();
같은 위키에 대해서 latest_wiki의 id랑 wiki_content의 id는 같지 않음 그래서 이렇게 조회하면 안됌.. 그래서 최신 위키의 버전이랑 wiki id로 wiki_content를 조회해야한다는 거임

2024-09-13 09:08 UTC, jimnyy commented on backend/src/main/java/org/example/backend/Wiki/Service/WikiService.java
> +        return wikiScrapRepository.findByUserIdAndWikiContentId(userId, latestWiki.getId()).isPresent();
수정 했슴다

2024-09-13 09:08 UTC, merged