[Feat] 위키 이전버전 목록 조회 API (#33)
beyond-sw-camp/be06-fin-SENAGAE-Enadu pull request #217
Opened 2024-09-18 21:47 UTC by jimnyy

## 연관 이슈
close #33 

## 작업 내용
📌사용자가 선택한 위키의 이전 버전 목록 조회
- 페이징 처리 및 정렬 설정(createdAt 기준 내림차순)

## 스크린샷 (선택)
![image](https://github.com/user-attachments/assets/99d9a886-b26c-413b-8b46-dd1a2c0e8b93)

## 리뷰 요구사항 혹은 기타 (선택)

2024-09-18 23:56 UTC, ashd89 commented
LGTM

2024-09-19 03:09 UTC, sue06004 requested changes
페이지만 바꾸면될듯

2024-09-19 03:09 UTC, sue06004 commented on backend/src/main/java/org/example/backend/Wiki/Service/WikiService.java
> +        Pageable pageable = PageRequest.of(getWikiVersionListReq.getPage(), getWikiVersionListReq.getSize(), Sort.by(Sort.Direction.DESC, "createdAt"));
페이지 뭐임?

2024-09-19 04:50 UTC, jimnyy commented on backend/src/main/java/org/example/backend/Wiki/Service/WikiService.java
> +        Pageable pageable = PageRequest.of(getWikiVersionListReq.getPage(), getWikiVersionListReq.getSize(), Sort.by(Sort.Direction.DESC, "createdAt"));
뭐가요; 페이징 처리 하기로 했는데요;

2024-09-19 06:02 UTC, merged