[Feat] 회원가입 시 이메일 인증 api 구현(#3)
beyond-sw-camp/be06-fin-SENAGAE-Enadu pull request #235
Opened 2024-09-21 13:01 UTC by dlrkdms125

## 연관 이슈
close #3 

## 작업 내용
이메일 인증 로직은 다음과 같음
1. 회원은 인증 받을 이메일을 요청에 포함하여 서버에 보냄
2. 서버는 일정 시간 동안 인증 코드를 발행함
3. 서버는 인증 코드를 회원에게 받은 이메일로 전송함
4. 회원은 입력 받은 인증 코드를 요청에 포함하여 서버에 보냄
5. 회원의 verify의 상태는 true가 됨

## 스크린샷 (선택)
<img width="781" alt="image" src="https://github.com/user-attachments/assets/e0e5de65-818c-4382-9443-c1002c202020">
<img width="933" alt="image" src="https://github.com/user-attachments/assets/9472e86c-5103-4cca-baf6-737dd4965652">
<img width="1201" alt="image" src="https://github.com/user-attachments/assets/0270eab7-a5df-42fe-9756-869a088e2fcd">

## 리뷰 요구사항 혹은 기타 (선택)

2024-09-22 14:19 UTC, sue06004 approved these changes
굿

2024-09-22 14:19 UTC, sue06004 commented on backend/src/main/java/org/example/backend/EmailVerify/Controller/EmailVerifyController.java
> +@CrossOrigin(origins = "http://localhost:8081")
이건 지워줘

2024-09-22 14:19 UTC, sue06004 commented on backend/src/main/java/org/example/backend/User/Controller/UserController.java
> +        System.out.println("회원가입 요청 수신: " + userSignupReq.getEmail());
print문은 보통 사용안해서 테스트할 때만 쓰고 push할 땐 지워주는게 좋아

2024-09-23 01:59 UTC, sue06004 requested changes
진짜 거의다 왔어

2024-09-23 01:59 UTC, sue06004 commented on backend/src/main/java/org/example/backend/EmailVerify/Controller/EmailVerifyController.java
> +    public BaseResponse<String> verify(@RequestParam String email, @RequestParam String uuid){
@RequestBody 써주세요

2024-09-23 02:03 UTC, dyun23 commented on backend/src/main/java/org/example/backend/Common/GlobalMessage.java
> +}
이거 글로벌 메시지 그냥 없애고 서비스에서 하는게 좋을 것 같앙

2024-09-23 03:02 UTC, merged