[Feat] 이메일 인증 페이지 생성, axios 연결, 닉네임 중복 확인 수정
beyond-sw-camp/be06-fin-SENAGAE-Enadu pull request #248
Opened 2024-09-22 12:41 UTC by dlrkdms125

## 연관 이슈
close #

## 작업 내용
닉네임 중복 수정 
이메일 인증 페이지 생성, axios 연결
1. 이메일 인증 페이지 만들고 routing 설정
2. 해당 페이지에서 api 호출
3. 이메일에서 링크를 클릭하면 우리 페이지가 뜨고 뜨는 순간 api 호출되어서 email, uuid 날라가고
4. 백엔드에서 확인한 후 결과값을 응답으로 보냄
5. 프론트에서 응답이 성공
6. 로그인 버튼을 누르면 /login 경로로 이동

## 스크린샷 (선택)
화면 기록 2024-09-22 오후 9.24.15.mov

## 리뷰 요구사항 혹은 기타 (선택)

2024-09-22 12:53 UTC, jimnyy commented
귯걸

2024-09-22 14:14 UTC, sue06004 requested changes
좀만 다듬으면 될듯

2024-09-22 14:14 UTC, sue06004 commented on frontend/src/pages/EmailVerifyPage.vue
> +                const response = await axios.get(`http://localhost:8080/email/verify`, {
store로 옮겨주세요

2024-09-22 14:14 UTC, sue06004 commented on frontend/src/pages/EmailVerifyPage.vue
> +            message: '',
이거는 어디서 쓰는거야?

2024-09-22 14:14 UTC, sue06004 commented on frontend/src/pages/EmailVerifyPage.vue
> +                if (response.status === 302) {
이부분은 백엔드에서 주는 응답에 따라서 처리를 해야돼서 바꿔야할듯

2024-09-22 14:14 UTC, sue06004 commented on frontend/src/store/useUserStore.js
> +                if(selectedProfileFile){
이거 저번에 삭제 하지 않았었나?

2024-09-22 23:42 UTC, dlrkdms125 commented on frontend/src/pages/EmailVerifyPage.vue
> +                if (response.status === 302) {
response.data.code로 해?

2024-09-23 02:02 UTC, sue06004 requested changes
진짜 다옴

2024-09-23 02:02 UTC, sue06004 commented on frontend/src/store/useUserStore.js
> +                        params: {
param으로 보내면 안돼

2024-09-23 02:02 UTC, sue06004 commented on frontend/src/pages/EmailVerifyPage.vue
> +            isVerified: false, // 인증 상태
필요없을것같아

2024-09-23 02:02 UTC, sue06004 commented on frontend/src/store/useUserStore.js
> +                        this.isverified = true; // 인증 성공 상태로 변경
이건 굳이 안해줘도 될듯 그냥 isverified 변수가 없어도 괜찮을것같아

2024-09-23 02:52 UTC, merged