[Feat] 포인트 부여/차감 로직 완성 (#423)
beyond-sw-camp/be06-fin-SENAGAE-Enadu pull request #424
Opened 2024-10-06 09:52 UTC by sue06004

## 연관 이슈
close #423 

## 작업 내용
- 위키 수정, 답변 작성, 답변 채택, 에러아카이브 추천/비추천, 답변 추천/비추천 포인트 부여/차감
- 추천/비추천은 해당 메서드가 실행되기 전에 추천수와 비추천 수를 ThreadLocal에 저장해 둔 다음에 AfterReturning 했을 때 변경 된 값으로 포인트 부여 및 차감

## 스크린샷 (선택)

## 리뷰 요구사항 혹은 기타 (선택)
- ThreadLocal은 해당 스레드에서만 적용되는 변수. 만약 이걸 안쓰고 그냥 변수를 사용하면 다른 스레드에서 접근이 가능해 코드가 꼬임

2024-10-06 11:51 UTC, ashd89 requested changes

2024-10-06 11:51 UTC, ashd89 commented on backend/src/main/java/org/example/backend/Point/Aop/PointAop.java
> +    }
qna의 경우 좋아요와 싫어요가 메소드가 나뉘어져 있어서 문제 없을 거 같은데, 에러 아카이브의 경우 하나의 메소드로 좋아요 및 싫어요를 처리하기 때문에, 좋아요 수가 10->9가 되는 것과 싫어요 수가 4->5가 되는 과정이 동시에 일어날 수 있는데 이에 대한 처리가 어떻게 되는 건지 궁금합니다!

2024-10-06 14:14 UTC, jimnyy commented
귯

2024-10-07 00:02 UTC, sue06004 commented on backend/src/main/java/org/example/backend/Point/Aop/PointAop.java
> +    }
위에 if문에서는 좋아요 수가 9->10이 되는거랑 10->9되는걸 처리하고, 밑에 if문에선 싫어요에 관해서 처리해서 물어본 경우는 두번 point가 부여/차감이 일어나게됩니다.

2024-10-07 02:31 UTC, merged