Fe/fix/update/invalid/url
beyond-sw-camp/be06-fin-SENAGAE-Enadu pull request #542
Opened 2024-10-18 07:26 UTC by dlrkdms125

## 연관 이슈
close #541 

## 작업 내용
수정 페이지에서 유효하지 않는 url 입력시 예외 처리

## 스크린샷 (선택)

## 리뷰 요구사항 혹은 기타 (선택)

2024-10-18 11:23 UTC, sue06004 requested changes

2024-10-18 11:23 UTC, sue06004 commented on frontend/src/pages/ErrorArchiveUpdatePage.vue
> +        if (articleData.authorId !== loggedInUserId) {
authorId는 어디에 써있는건아요? 백엔드  GetErrorArchiveEditDetailRes.java 이 코드에는 userId밖에 없는데... 다시 제대로 확인한번 부탁드려요

2024-10-18 11:23 UTC, sue06004 commented on frontend/src/pages/ErrorArchiveUpdatePage.vue
> +              superCategory: articleData.superCategory,
여기도 백엔드 pr올라온거 보면 req에 superCategory라는게 없는것 같은데...

2024-10-19 05:09 UTC, dyun23 commented
엥 이거 저 밑에 있는 pr이랑 내용 똑같은 것 같은데??

2024-10-19 05:12 UTC, dyun23 requested changes

2024-10-19 05:12 UTC, dyun23 commented on frontend/src/pages/ErrorArchiveUpdatePage.vue
> +              superCategory: articleData.superCategory,
그 백엔드 pr 올라온 메소드는 다른거고 이건 원래 메소드 쓰고 있어서 상관 없을 것 같은데 문제가 새로 만든 메소드를 프론트에서 안 쓰고 있는 것 같아용

2024-10-19 13:21 UTC, closed without merging