Fe/feat/qna/ai answer state
beyond-sw-camp/be06-fin-SENAGAE-Enadu pull request #555
Opened 2024-10-18 10:14 UTC by ashd89

## 연관 이슈
close #448 

## 작업 내용
수정 권한이 없는 사용자의 수정 사이트 접속 에러 처리
수정 권한이 있지만, 수정 요건을 만족하지 않는 질문 글에 url을 통한 수정 페이지 접근에 대한 에러 처리
수정 및 삭제 조건에 ai 답변만 있는 case를 제외
ai 답변에 대한 좋아요 및 싫어요/ 댓글 기능 비활성화

## 스크린샷 (선택)

## 리뷰 요구사항 혹은 기타 (선택)

2024-10-18 10:54 UTC, dyun23 commented
ai 답변 누가 한지 모르겠는데 진짜 이쁘네요

2024-10-18 11:45 UTC, sue06004 requested changes

2024-10-18 11:45 UTC, sue06004 commented on frontend/src/components/Qna/Refactor/QnaEditComponent.vue
> +    await this.enter();
this.enter에서 이미 입력된 답변이 있을 때 router push를 하긴 하는데 그러면 이 밑에 코드도 안돌아가게 해주세요

2024-10-19 05:41 UTC, dyun23 requested changes

2024-10-19 05:41 UTC, dyun23 commented on frontend/src/components/Qna/Detail/QnaAnswerDetailComponent.vue
> +      isLoggedIn: false,
이 변수를 여기에 저장을 하는게 맞나? 그냥 유저 스토어꺼 들고오면 안 되냐?

2024-10-19 05:41 UTC, dyun23 commented on frontend/src/components/Qna/Detail/QnaAnswerDetailComponent.vue
> +      isLoggedIn: false,
근데 이거 변수 어디서 설정해주고 있어?

2024-10-19 05:41 UTC, dyun23 commented on frontend/src/components/Qna/Refactor/QnaEditComponent.vue
> +      if (useQnaStore().qnaDetail !== undefined && useQnaStore().qnaDetail.answerCnt !== 0) {
이거 undefined가 이렇게 undefined로 쓰면 잡혀? 신기하네...

2024-10-19 10:02 UTC, sue06004 commented on frontend/src/components/Qna/Refactor/QnaEditComponent.vue
> +      if (useQnaStore().qnaDetail !== undefined && useQnaStore().qnaDetail.answerCnt !== 0) {
> 이거 undefined가 이렇게 undefined로 쓰면 잡혀? 신기하네...

오히려 undefined로 해야 잡히더라.. null로하면 안되고

2024-10-19 11:19 UTC, ashd89 commented on frontend/src/components/Qna/Refactor/QnaEditComponent.vue
> +    await this.enter();
이거 이후 코드에서 수정했어요!

2024-10-19 11:19 UTC, ashd89 commented on frontend/src/components/Qna/Detail/QnaAnswerDetailComponent.vue
> +      isLoggedIn: false,
이후 pr에서 고쳐놓았습니다.

2024-10-19 12:18 UTC, merged