Fe/feat/qna/login comment
beyond-sw-camp/be06-fin-SENAGAE-Enadu pull request #559
Opened 2024-10-18 11:01 UTC by ashd89

## 연관 이슈
close #286 

## 작업 내용
로그인하지 않은 사용자의 댓글 대댓글 보기 권한 부여 및 작성 권한 조정

## 스크린샷 (선택)

## 리뷰 요구사항 혹은 기타 (선택)

2024-10-18 11:48 UTC, sue06004 approved these changes
굿

2024-10-18 17:03 UTC, jimnyy commented
귯

2024-10-19 05:48 UTC, dyun23 requested changes
QnaCommentDetailComponent 빼고 밑에 pr이랑 똑같은 것 같아요 확인 해주세요

2024-10-19 05:48 UTC, dyun23 commented on frontend/src/components/Common/AdditionalInfoComponent.vue
> -          if (this.detail.answers.length === 0) {
엥 이거 밑에 pr에도 수정한 커밋 있던 것 같은데

2024-10-19 05:48 UTC, dyun23 commented on frontend/src/components/Qna/Detail/QnaAnswerDetailComponent.vue
> +      }
여기 파일도

2024-10-19 05:48 UTC, dyun23 commented on frontend/src/components/Qna/Detail/QnaCommentDetailComponent.vue
> +    this.isLoggedIn = useUserStore().isLoggedIn;
여기도 그냥 스토어에 있는거 저장 안 하고 그대로 들고와서 쓰는게 좋을듯?

2024-10-19 05:48 UTC, dyun23 commented on frontend/src/components/Qna/Refactor/QnaEditComponent.vue
> +    await this.enter();
이 파일도 밑에 pr에 있던 것 같은데

2024-10-19 12:18 UTC, merged